<?xml version="1.0"?>

<robot name="desherborator" xmlns:xacro="http://ros.org/wiki/xacro">

    <link name="LIDAR">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="0.03" length="0.04"/>
        </geometry>
        </visual>
        <xacro:default_inertial mass="0.1"/>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="Mat"/>
        <child link="LIDAR"/>
        <origin xyz="0 0 0.075" rpy="0 0 0"/>
    </joint>

    <gazebo reference="LIDAR">
        <material>Gazebo/Orange</material>
        <sensor type="ray" name="lidar_sensor">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>40</update_rate>
        <ray>
            <scan>
            <horizontal>
                <samples>20</samples>
                <resolution>1</resolution>
                <min_angle>-3.0</min_angle>
                <max_angle>3.0</max_angle>
            </horizontal>
            </scan>
            <range>
            <min>0.120</min>
            <max>12</max>
            <resolution>0.015</resolution>
            </range>
            <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
            </noise>
        </ray>
        <plugin name="gazebo_ros_lds_lfcd_controller" filename="libgazebo_ros_laser.so">
            <topicName>/laser_scan</topicName>
            <!-- ENTER FRAME NAME -->
            <frameName>LIDAR</frameName>
        </plugin>
        </sensor>
    </gazebo>

    <joint name="camera_joint" type="fixed">
        <parent link="Chassis"/>
        <axis xyz="0 1 0" />
        <origin xyz="${ChassisWidth} 0 ${ChassisHeight/2}" rpy="0 0 0"/>
        <child link="Camera"/>
    </joint>

    <!-- Camera -->
    <link name="Camera">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>


    <gazebo reference="Camera">
        <material>Gazebo/Green</material>
        <sensor type="camera" name="main_camera">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                <width>1280</width>
                <height>720</height>
                <format>R8G8B8</format>
                </image>
                <clip>
                <near>0.02</near>
                <far>300</far>
                </clip>
                <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <topicName>camera</topicName>
                <frameName>Camera</frameName>
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>main_camera</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>


    <link name="LASER">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="0.025" length="0.15"/>
        </geometry>
        </visual>
        <xacro:default_inertial mass="0.1"/>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="BrasC3"/>
        <child link="LASER"/>
        <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
    </joint>


    <gazebo reference="LASER">
        <material>Gazebo/Blue</material>
        <sensor type="ray" name="laser_sensor">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>5</update_rate>
        <ray>
            <scan>
            <horizontal>
                <samples>10</samples>
                <resolution>1</resolution>
                <min_angle>0.0</min_angle>
                <max_angle>0.1</max_angle>
            </horizontal>
            </scan>
            <range>
            <min>0.120</min>
            <max>12</max>
            <resolution>0.015</resolution>
            </range>
            <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
            </noise>
        </ray>
        <plugin name="gazebo_ros_lds_lfcd_controller" filename="libgazebo_ros_laser.so">
            <topicName>/laser</topicName>
            <!-- ENTER FRAME NAME -->
            <frameName>LASER</frameName>
        </plugin>
        </sensor>
    </gazebo>

    <link name="GPS_link">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="0.005" length="0.005"/>
        </geometry>
        </visual>
        <xacro:default_inertial mass="0.05"/>
    </link>

    <joint name="GPS_joint" type="fixed">
        <parent link="Chassis"/>
        <child link="GPS_link"/>
        <origin xyz="-0.01 0 0" rpy="0 0 0"/>
    </joint>

<gazebo>
    <plugin filename="libhector_gazebo_ros_gps.so" name="GPS_link">
        <alwayson>true</alwayson>
        <updateRate>10</updateRate> 
        <bodyName>GPS_link</bodyName>
        <topicName>/fix</topicName> 
        <velocityTopicName>/vel</velocityTopicName>
        <drift>5.0 5.0 5.0</drift> 
        <gaussianNoise>0.0000001 0.0000001 0.0000001</gaussianNoise>
        <velocityDrift>0 0 0</velocityDrift> 
        <velocityGaussianNoise>0.0000001 0.0000001 0.0000001</velocityGaussianNoise> 
    </plugin> 
</gazebo>

</robot>
