<xml version="1.0"?>
<!-- Create the robot sensors. The robot has the following sensors :
    Lidar : an hokuyo sensor
    Camera : Front camera of the robot
    Laser : the laser for burning the weeds 
    Author : Elodie NOELE --> 

<xacro:include filename="./desherborator.parameters.xacro" />
<xacro:include filename="./desherborator.materials.xacro" />
<xacro:include filename="./desherborator.joint.xacro" />

<xacro:property name="chassisHeight" value="0.1"/>

<robot name="desherborator" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="LIDAR">
        <gazebo reference="LIDAR">
            <material name= "black"/>
            <sensor type="ray" name="lidar_sensor">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>5</update_rate>
            <ray>
                <scan>
                <horizontal>
                    <samples>720</samples>
                    <resolution>1</resolution>
                    <min_angle>0.0</min_angle>
                    <max_angle>6.28319</max_angle>
                </horizontal>
                </scan>
                <range>
                <min>0.120</min>
                <max>12</max>
                <resolution>0.015</resolution>
                </range>
                <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_lds_lfcd_controller" filename="libgazebo_ros_laser.so">
                <topicName>scan</topicName>
                <!-- ENTER FRAME NAME -->
                <frameName>lidar</frameName>
            </plugin>
            </sensor>
        </gazebo>

        <link name="lidar">
            <visual>
            <origin xyz="0 0 -0.03" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="{lidarRadius}" length="{lidarLength}"/>
            </geometry>
            </visual>
            <xacro:default_inertial mass="0.1"/>
        </link>

        <joint name="lidar_joint" type="fixed">
            <parent link="chassis"/>
            <child link="lidar"/>
            <origin xyz="0.15 0 0.23" rpy="0 0 0"/>
        </joint>
    </xacro:macro>
  

    <xacro:macro name="Camera">
        <gazebo reference="Camera">
            <material name= "red"/>
            <sensor type="camera" name="main_camera">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                <width>1280</width>
                <height>720</height>
                <format>R8G8B8</format>
                </image>
                <clip>
                <near>0.02</near>
                <far>300</far>
                </clip>
                <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>main_camera</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
            </sensor>
        </gazebo>
        
        <joint name="camera_joint" type="fixed">
            <parent link="chassis"/>
            <axis xyz="0 1 0" />
            <origin xyz="${chassisWidth} 0 ${chassisHeight/2}" rpy="0 0 0"/>
            <child link="camera_link"/>
        </joint>

        <!-- Camera -->
        <link name="camera_link">
            <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
            </geometry>
            </collision>

            <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
            </geometry>
            <material name="red"/>
            </visual>

            <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
        </link>
    </xacro:macro>

    <xacro:macro name="LASER">
        <gazebo reference="LASER">
            <material name= "blue"/>
            <sensor type="ray" name="laser_sensor">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>5</update_rate>
            <ray>
                <scan>
                <horizontal>
                    <samples>720</samples>
                    <resolution>1</resolution>
                    <min_angle>0.0</min_angle>
                    <max_angle>0.1</max_angle>
                </horizontal>
                </scan>
                <range>
                <min>0.120</min>
                <max>12</max>
                <resolution>0.015</resolution>
                </range>
                <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_lds_lfcd_controller" filename="libgazebo_ros_laser.so">
                <topicName>scan_laser</topicName>
                <!-- ENTER FRAME NAME -->
                <frameName>laser</frameName>
            </plugin>
            </sensor>
        </gazebo>

        <link name="laser">
            <visual>
            <origin xyz="0 0 -0.03" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="{laserRadius}" length="{laserLength}"/>
            </geometry>
            </visual>
            <xacro:default_inertial mass="0.1"/>
        </link>

        <joint name="laser_joint" type="fixed">
            <parent link="chassis"/>
            <child link="laser"/>
            <origin xyz="0.15 0 0.23" rpy="0 0 0"/>
        </joint>
    </xacro:macro>


</robot>



